---
- hosts: docker
  user: pradip
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:

    - name: pull an image
      docker_image:
        name: tomcat:9
        source: pull

    - name: Start Docker container
      docker_container:
        name: tomcat
        image: tomcat:9
        ports:
          - "8082:8080"
        volumes:
          - /mnt/project/mnt/project/gameoflife-web/target/gameoflife.war:/usr/lib/tomcat/webapps
        state: started
        restart_policy: always

