---
- hosts: docker
  user: pradip
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:


    - name: pull an image
      docker_image:
        name: tomcat:9.0.73
        tag: 9.0.73
        source: pull

    - name: pull an image
      docker_image:
        name: docker
        source: pull

    - name: Start Docker 
      docker_container:
        image: docker
        name: docker-1
        state: started
        
    - name: creating volume
      file:
        path: /mnt/data
        state: directory    

    - name: copy
      action: copy src=/mnt/project/gameoflife-web/target/gameoflife.war dest=/mnt/data

    - name: Start Docker container
      docker_container:
        name: tomcat
        image: tomcat:9.0.73
        ports:
          - "8082:8080"
        volumes:
          - "/mnt/data:/usr/local/tomcat/webapps"
        state: started
        restart_policy: always

