---
- hosts: devlinux
  user: pradip
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:

    - name: install tomcat
      action: get_url url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.zip dest=/mnt/

    - name: unzip tomcat
      unarchive:
        src: /mnt/apache-tomcat-9.0.73.zip
        dest: /mnt/
        remote_src: yes

    - name: copy war
      action: copy src=/mnt/data/gameoflife-web/target/gameoflife.war dest=/mnt/apache-tomcat-9.0.73/webapps
      
    - name: install java
      command: sudo yum install java-1.8.0-openjdk-devel.x86_64 -y

    - name: permission
      command: chmod -R 777 /mnt

    - name: start tomcat
      command: cd  /mnt/apache-tomcat-9.0.73/bin | ./startup.sh
